# Cloudflare Pages Configuration for Lead Finder
name = "lead-finder"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
# Environment variables for production
# These will be set in Cloudflare Pages dashboard

[env.preview]
# Environment variables for preview deployments
